// Code generated by MockGen. DO NOT EDIT.
// Source: tech_challenge/internal/interfaces (interfaces: IKitchenOrderDataSource)

package mock_interfaces

import (
	reflect "reflect"
	dtos "tech_challenge/internal/application/dtos"
	daos "tech_challenge/internal/daos"

	gomock "github.com/golang/mock/gomock"
)

// MockIKitchenOrderDataSource is a mock of IKitchenOrderDataSource interface.
type MockIKitchenOrderDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockIKitchenOrderDataSourceMockRecorder
}

// MockIKitchenOrderDataSourceMockRecorder is the mock recorder for MockIKitchenOrderDataSource.
type MockIKitchenOrderDataSourceMockRecorder struct {
	mock *MockIKitchenOrderDataSource
}

// NewMockIKitchenOrderDataSource creates a new mock instance.
func NewMockIKitchenOrderDataSource(ctrl *gomock.Controller) *MockIKitchenOrderDataSource {
	mock := &MockIKitchenOrderDataSource{ctrl: ctrl}
	mock.recorder = &MockIKitchenOrderDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIKitchenOrderDataSource) EXPECT() *MockIKitchenOrderDataSourceMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockIKitchenOrderDataSource) Insert(arg0 daos.KitchenOrderDAO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockIKitchenOrderDataSourceMockRecorder) Insert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIKitchenOrderDataSource)(nil).Insert), arg0)
}

// FindByID mocks base method.
func (m *MockIKitchenOrderDataSource) FindByID(arg0 string) (daos.KitchenOrderDAO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0)
	ret0, _ := ret[0].(daos.KitchenOrderDAO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIKitchenOrderDataSourceMockRecorder) FindByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIKitchenOrderDataSource)(nil).FindByID), arg0)
}

// FindAll mocks base method.
func (m *MockIKitchenOrderDataSource) FindAll(arg0 dtos.KitchenOrderFilter) ([]daos.KitchenOrderDAO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].([]daos.KitchenOrderDAO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIKitchenOrderDataSourceMockRecorder) FindAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIKitchenOrderDataSource)(nil).FindAll), arg0)
}

// Update mocks base method.
func (m *MockIKitchenOrderDataSource) Update(arg0 daos.KitchenOrderDAO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIKitchenOrderDataSourceMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIKitchenOrderDataSource)(nil).Update), arg0)
}
