issues:
  exclude-rules:
    # Exclude deprecated warnings for AWS SDK v2 migration (temporary)
    - linters:
        - staticcheck
      text: "SA1019.*aws\\.Endpoint.*is deprecated"
    - linters:
        - staticcheck
      text: "SA1019.*aws\\.EndpointResolverFunc.*is deprecated"
    - linters:
        - staticcheck
      text: "SA1019.*config\\.WithEndpointResolver.*is deprecated"