// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/kitchen-orders/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KitchenOrders"
                ],
                "summary": "List all kitchenOrders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schemas.KitchenOrderResponseSchema"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/schemas.ErrorMessageSchema"
                        }
                    }
                }
            }
        },
        "/kitchen-orders/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KitchenOrders"
                ],
                "summary": "Get a kitchenOrder by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "KitchenOrder ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.KitchenOrderResponseSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidKitchenOrderDataErrorSchema"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.KitchenOrderNotFoundErrorSchema"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "schemas.ErrorMessageSchema": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Internal server error"
                }
            }
        },
        "schemas.InvalidKitchenOrderDataErrorSchema": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid kitchen order data"
                }
            }
        },
        "schemas.KitchenOrderNotFoundErrorSchema": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Kitchen order not found"
                }
            }
        },
        "schemas.KitchenOrderResponseSchema": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-10-01T12:00:00Z"
                },
                "order_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "slug": {
                    "type": "string",
                    "example": "001"
                },
                "status": {
                    "type": "string",
                    "example": "Pronto"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-10-01T12:00:00Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/v1",
	Schemes:          []string{"http"},
	Title:            "Tech Challenge API",
	Description:      "This is an API for a tech challenge.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
